version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    environment:
      PYTHONBUFFERED: 1
    volumes:
      - .:/app